rose_planner_node:
  ros__parameters:
    use_sim_time: true
    odom_topic: /Odometry
    goal_topic: /rose_goal
    target_frame: map
    robot_size: [0.3, 0.3]
    use_control_output: true
    dynamic_replan: false
    default_wz: 0.0
    path_search:
      a_star: 
        clearance_weight: 2.0
        obstacle_penalty_weight: 10.0
        heuristic_weight: 1.0
    resampler:
        expected_speed: 3.0
        max_acc: 3.0
        dt: 0.1
    trajectory_opt:
      smooth_weight: 3.0
      obstacle_weight: 700.0
      time_weight: 30.0
      base_scale: 100.0
    mpc_control:
      fps: 50
      dt: 0.05
      max_iter: 20
      predict_steps: 20
      max_speed: 2.5
      max_accel: 30.0
      delay_time: 0.0
      blind_radius: 0.3
      Q: [150.0,150.0,10.0,10.0]
      Rd: [1.0,0.05]
      R: [0.1,0.1]
    rose_map:
      log_time: true
      pointcloud_topic: /cloud_registered
      target_frame: map
      sensor_frame: front_mid360
      max_update_rate: 10
      occ_map:
        log_hit: 0.85
        log_free: -0.3
        log_min: -5.0
        log_max: 10.0
        occ_th: 0.0       
        min_shift: 1
        timeout: 150.5
        unknown_is_occupied: false
        use_ray: true
        max_ray_range: 20.0
        voxel_map:
          center: [0.0, 0.0, 0.0]
          size: [17.0, 17.0, 1.0]
          voxel_size: 0.04
      bin_map:
        voxel_size: 0.1
        max_slope_deg: 30.0
        static_map_path: "/home/hy/rose_nav/src/bringup_nav/map/simulation/rmuc_2024.yaml"
      esdf:
        use_diagonals: true
        size: [17.0, 17.0]
      